/** @type {import('lighthouse').Config} */
module.exports = {
  ci: {
    collect: {
      settings: {
        preset: "desktop" === process.env.LH_PRESET ? "desktop" : undefined,
        formFactor: "mobile",
        throttling: {
          rttMs: 150,
          throughputKbps: 1638.4,
          cpuSlowdownMultiplier: 4,
          requestLatencyMs: 0,
          downloadThroughputKbps: 0,
          uploadThroughputKbps: 0,
        },
        throttlingMethod: "devtools",
        screenEmulation: {
          mobile: true,
          width: 375,
          height: 667,
          deviceScaleFactor: 2,
          disabled: false,
        },
        onlyCategories: ["performance", "accessibility", "best-practices", "seo"],
      },
      numberOfRuns: 3,
    },
    assert: {
      assertions: {
        "largest-contentful-paint": ["error", { maxNumericValue: 2500 }],
        "cumulative-layout-shift": ["error", { maxNumericValue: 0.1 }],
        "total-blocking-time": ["error", { maxNumericValue: 200 }],
        "first-contentful-paint": ["warn", { maxNumericValue: 1800 }],
        "speed-index": ["warn", { maxNumericValue: 3400 }],
        "categories:performance": ["error", { minScore: 0.9 }],
        "categories:accessibility": ["error", { minScore: 0.95 }],
        "categories:best-practices": ["error", { minScore: 0.95 }],
        "categories:seo": ["error", { minScore: 0.95 }],
        "resource-summary:script:size": ["error", { maxNumericValue: 500000 }],
        "resource-summary:stylesheet:size": ["warn", { maxNumericValue: 70000 }],
        "resource-summary:image:size": ["warn", { maxNumericValue: 500000 }],
        "resource-summary:font:size": ["warn", { maxNumericValue: 100000 }],
        "resource-summary:total:size": ["error", { maxNumericValue: 1500000 }],
        "modern-image-formats": "error",
        "uses-responsive-images": "error",
        "color-contrast": "error",
        "target-size": "error",
        "meta-viewport": "error",
        "image-alt": "error",
        "label": "error",
        "link-name": "error",
        "button-name": "error",
        "aria-required-attr": "error",
        "document-title": "error",
        "html-has-lang": "error",
        "viewport": "error",
        "font-size": "error",
        "errors-in-console": "error",
        "is-on-https": "error",
      },
    },
    upload: {
      target: process.env.LHCI_TARGET || "filesystem",
      outputDir: process.env.LHCI_OUTPUT_DIR || ".lighthouseci",
      reportFilenamePattern: "%%PATHNAME%%-%%DATETIME%%-report.%%EXTENSION%%",
    },
  },
};
